server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/oauth2?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&serverTimezone=UTC
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    password:
    port: 6379
    timeout: 30000

security:
  jwt:
    signingKey: zhsSignKey
  oauth2:
    storeType: redis